FROM python:3.11-slim
WORKDIR /app
COPY . /app
RUN python -m pip install --upgrade pip setuptools wheel
RUN pip install --no-cache-dir -r requirements.txt
ENV BOT_TOKEN=${BOT_TOKEN}
CMD ["python", "bot.py"]
